// MicroGrid — the 64×64 tile representation of one macro cell.
// Generated by ChunkGenerator; consumed by the render and combat layers.
// No game logic lives here — pure data container.

export const CHUNK_SIZE = 64;

export class MicroGrid {
  constructor(macroX, macroY) {
    const N        = CHUNK_SIZE * CHUNK_SIZE;
    this.macroX    = macroX;
    this.macroY    = macroY;

    this.elevation = new Float32Array(N);   // 0–1, per-tile world elevation
    this.ground    = new Uint8Array(N);     // GROUND.* surface type
    this.obstacle  = new Uint8Array(N);     // OBSTACLE.* on-tile object
    this.variant   = new Uint8Array(N);     // 0–15 visual sub-variant
    this.passable  = new Uint8Array(N);     // 0|1 — precomputed from obstacle
    this.overlays  = new Uint8Array(N);     // road/river bits (future): N=1 E=2 S=4 W=8
    this.river     = new Uint8Array(N);     // 0=none 1=bed 2=bank 3=rapids

    // Computed slope metadata (stored for render/combat use)
    this.slopeDir  = 'flat';  // 'flat'|'N'|'NE'|'E'|'SE'|'S'|'SW'|'W'|'NW'
    this.slopeMag  = 0;       // rank difference magnitude 0–6
  }

  idx(x, y) { return y * CHUNK_SIZE + x; }

  get(x, y) {
    const i = this.idx(x, y);
    return {
      elevation: this.elevation[i],
      ground:    this.ground[i],
      obstacle:  this.obstacle[i],
      variant:   this.variant[i],
      passable:  this.passable[i],
    };
  }
}
